[alembic]
# path to migration scripts
script_location = infrastructure/sql/migrations

# database url
sqlalchemy.url = postgresql+psycopg2://postgres:your_password_here@localhost:5432/markets

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library that can be
# installed by adding `alembic[tz]` to the pip requirements
# warning: this setting is deprecated in favor of the timezone setting
# tz = UTC

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment file as a standalone script.
# By default, the environment file is run within the same
# process as Alembic, so that the application is loaded
# while the environment runs. This is usually what you want,
# but in a testing scenario, or if you need to debug the
# environment file, it can be helpful to run it standalone.
# standalone_mode = false

# set to 'true' to have the standalone environment file automatically
# include the migration environment context. This is typically
# useful for testing.
# standalone_mode_with_migrations = false

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic
qualname =

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S